site_name: John Wang's Site
site_url: https://grokify.github.io
docs_dir: src
theme: readthedocs
markdown_extension:
    - attr_list
nav:
    - 'Home': 'index.md'
    - 'Innovation':
        - 'Patents (3)': 'patents/index.md'
        - 'Presentations (3)': 'presentations/index.md'
        - 'Publications (2)': 'publications/index.md'
    - 'Awards':
        - 'API (7)': 'awards/index.md'
    - 'Certificates':
        - 'API (11)': 'certificates/api.md'
        - 'Algorithms (3)': 'certificates/algorithms.md'
        - 'Appreciation (3)': 'certificates/appreciation.md'
        - 'Artificial Intelligence (135)': 'certificates/artificial-intelligence.md'
        - 'Artificial Intelligence: ML (20)': 'certificates/artificial-intelligence-ml.md'
        - 'Board of Directors (5)': 'certificates/board-of-directors.md'
        - 'Cloud Computing (47)': 'certificates/cloud-computing.md'
        - 'Customer Service (5)': 'certificates/customer-service.md'
        - 'Data (19)': 'certificates/data.md'
        - 'Data Science (7)': 'certificates/data-science.md'
        - 'Design Thinking (4)': 'certificates/design-thinking.md'
        - 'DevOps (13)': 'certificates/devops.md'
        - 'Human Resources (13)': 'certificates/human-resources.md'
        - 'Information Technology (1)': 'certificates/information-technology.md'
        - 'Leadership (14)': 'certificates/leadership.md'
        - 'Management (28)': 'certificates/management.md'
        - 'Management Consulting (7)': 'certificates/management-consulting.md'
        - 'Marketing (7)': 'certificates/marketing.md'
        - 'Nonprofit (9)': 'certificates/nonprofit.md'
        - 'Observability and Reliability (19)': 'certificates/observability-and-reliability.md'
        - 'Personal Development (9)': 'certificates/personal-development.md'
        - 'Product Design (2)': 'certificates/product-design.md'
        - 'Product Management (24)': 'certificates/product-management.md'
        - 'Programming (41)': 'certificates/programming.md'
        - 'Programming: QA (5)': 'certificates/programming-qa.md'
        - 'Quality Assurance (5)': 'certificates/quality-assurance.md'
        - 'Scrum (21)': 'certificates/scrum.md'
        - 'Security: AI (15)': 'certificates/security-ai.md'
        - 'Security: AppSec (54)': 'certificates/security-appsec.md'
        - 'Security: Compliance (8)': 'certificates/security-compliance.md'
        - 'Security: IDSec (22)': 'certificates/security-idsec.md'
        - 'Security: InfoSec (50)': 'certificates/security-infosec.md'
        - 'Security: SecOps (7)': 'certificates/security-secops.md'
        - 'Sports (6)': 'certificates/sports.md'
        - 'Strategy (7)': 'certificates/strategy.md'
        - 'TED Talks (7)': 'certificates/ted-talks.md'
